In [1]:
from sklearn.preprocessing import StandardScaler

In [2]:
data = [[0, 0], [0, 0], [1, 1], [1, 1]]

In [3]:
scaler = StandardScaler()

In [4]:
scaler.fit(data)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [5]:
scaler.mean_

array([0.5, 0.5])

In [6]:
scaler.var_

array([0.25, 0.25])

In [7]:
scaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [8]:
scaler.transform([[2, 2]])

array([[3., 3.]])

In [17]:
class MyStandardScaler:
    def _init_(self):
        self.data_mean_ = None
        self.data_var_ = None
        
    def fit(self, data):
        self.data_mean_ = np.mean(data, axis=0)
        self.data_var_ = np.var(data, axis=0)
        
    def transform(self, data):
        new_data = (np.array(data) - scaler.mean_) / (scaler.var_**(1/2))
        return new_data
    
    def fit_transform(self, data):
        self.fit(data)
        return self.transform(data)

In [10]:
import numpy as np

In [11]:
np.mean(data, axis=0)

array([0.5, 0.5])

In [12]:
np.var(data, axis=0)

array([0.25, 0.25])

In [16]:
(np.array(data) - scaler.mean_) / (scaler.var_**(1/2))

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [18]:
myscaler = MyStandardScaler()

In [19]:
data

[[0, 0], [0, 0], [1, 1], [1, 1]]

In [20]:
myscaler.fit(data)

In [22]:
myscaler.data_mean_

array([0.5, 0.5])

In [23]:
myscaler.data_var_

array([0.25, 0.25])

In [24]:
myscaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [25]:
myscaler_new = MyStandardScaler()

In [27]:
myscaler_new.fit_transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])